---
- name: Creando reporte OpenScap RHEL9
  ansible.builtin.command: oscap xccdf eval \
    --profile xccdf_org.ssgproject.content_profile_cis_server_l1 \    
    --report /root/rhel9_openscap_result/rhel9_reforzamiento_postremediacion_{{ inventory_hostname }}.html \
    /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
  register: rhel_9_reforzamiento_postremediacion
  ignore_errors: true
