---
- name: habilitacion de puertos http RHEL9
  ansible.builtin.include_tasks: rhel9/rhel9_firewall_http.yml

- name: habilitacion de puertos oracle RHEL9
  ansible.builtin.include_tasks: rhel9/rhel9_firewall_oracle.yml

- name: habilitacion de puertos sap RHEL9
  ansible.builtin.include_tasks: rhel9/rhel9_firewall_sap.yml

- name: habilitacion de puertos sial lobo RHEL9
  ansible.builtin.include_tasks: rhel9/rhel9_firewall_sial_lobo.yml

- name: habilitacion de puertos weblogic RHEL9
  ansible.builtin.include_tasks: rhel9/rhel9_firewall_weblogic.yml

- name: recoleccion de datos 
  ansible.builtin.include_tasks: rhel9/rhel9_recoleccion_informacion.yml