---
- name: inclusion de tareas de configuracion de sistema 
  ansible.builtin.include_tasks: "{{ system_settings_item }}"
  loop:
    # - configure_gnome_login_screen.yml
    # - configure_gnome_screen_locking.yml
    - configure_ipv6_settings_if_necessary.yml
    # - configure_rsyslogd_to_accept_remote_messages_if_acting_as_a_log_server.yml
    # - ensure_that_users_have_sensible_umask_values.yml
    # - gnome_media_settings.yml
    # - inspect_and_activate_default_firewalld_rules.yml
    - network_parameters_for_hosts_only.yml
    - network_related_kernel_runtime_parameters_for_hosts_and_routers.yml
    # - restrict_dynamic_mounting_and_unmounting_of_filesystems.yml
    # - restrict_partition_mount_options.yml
    - restrict_programs_from_dangerous_execution_patterns.yml
    # - set_lockouts_for_failed_password_attempts.yml
    # - set_password_quality_requirements.yml
    # - systemd-journald.yml
    # - verify_integrity_with_aide.yml
    # - verify_proper_storage_and_existence_of_password_hashes.yml
    # - warning_banners_for_system_accesses.yml
  loop_control:
    loop_var: system_settings_item