---
- name: Push to origin.
  ansible.builtin.shell: "cd /home/runner/reportes_openscap_servidores_rhel"
  delegate_to: localhost
  
- name: agregando archivos a repositorio git add
  ansible.builtin.command:
    cmd: git add .
    chdir: /home/runner/reportes_openscap_servidores_rhel 
  delegate_to: localhost

- name: ingresando el correo electronico
  ansible.builtin.command:
    cmd: git config --global user.email "sergioab1989@gmail.com"
    chdir: /home/runner/reportes_openscap_servidores_rhel
  delegate_to: localhost

- name: ingresando el usuario
  ansible.builtin.command:
    cmd: git config --global user.name "sergioab1989"
    chdir: /home/runner/reportes_openscap_servidores_rhel
  delegate_to: localhost

- name: Realizar commit de los cambios
  ansible.builtin.command:
    cmd: git commit -m "actualizacion de resultados de openscap {{ ansible_host }}"
    chdir: /home/runner/reportes_openscap_servidores_rhel 
  delegate_to: localhost

- name: Realizar commit de los cambios
  ansible.builtin.command:
    cmd: git push origin --force
    chdir: /home/runner/reportes_openscap_servidores_rhel 
  delegate_to: localhost
