---
#Uninstall CUPS Package
- name: Ensure cups is removed
  package:
    name: cups
    state: absent
  tags:
  - CCE-86300-1
  - NIST-800-53-CM-6(a)
  - NIST-800-53-CM-7(a)
  - NIST-800-53-CM-7(b)
  - disable_strategy
  - low_complexity
  - low_disruption
  - no_reboot_needed
  - package_cups_removed
  - unknown_severity