---
- name: Creando reporte OpenScap RHEL7 
  ansible.builtin.command: oscap xccdf eval \
    --profile xccdf_org.ssgproject.content_profile_cis_server_l1 \
    --report /root/rhel7_openscap_result/rhel7_reforzamiento_postremediacion_{{ inventory_hostname }}.html \
    /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
  register: rhel_7_reforzamiento_postremediacion
  ignore_errors: true
