---
- name: recoleccion de informacion para notificacion
  ansible.builtin.set_fact: 
    rhel7_recoleccion_miti: |
      {% if rhel7_recoleccion is defined and rhel7_recoleccion != "" %}         
          {{ rhel7_recoleccion }}                    
      {% endif %}

      Analisis de vulnerabilidades posterior a mitigacion

      Archivo openscap : /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
      Perfil utilizado : xccdf_org.ssgproject.content_profile_cis_server_l1

      {{ "Host escaneado:    " + inventory_hostname }}
      {{ "Direccion IP  :    " + ansible_host }}

      Vulnerabilidades encontradas en escaneo de openscap
      ---------------------------------------------------------------------
      Vulnerabilidades por remediar : {{ fail_count }}
      Vulnerabilidades remediadas   : {{ pass_count }}

      Para mayor informacion consultar archivo html openscap
      ---------------------------------------------------------------------
      Repositorio Bitbuket : http://172.27.213.17:17990/projects/ANSIBLE/repos/reportes_openscap_servidores_rhel/browse/{{ inventory_hostname }}/rhel7_reforzamiento_postremediacion_{{ inventory_hostname }}_{{ current_datetime }}.html
    
- name: Actualizacion Rhel7-Paso de variable RHEL7
  ansible.builtin.set_stats:
    data:
      rhel7_recoleccion_info: "{{ rhel7_recoleccion_miti }}"
