---
- name: Instalacion de OpenScap scanner - security-guide - utils
  ansible.builtin.yum:
    name:
      - openscap
      - openscap-utils
      - scap-security-guide
    state: latest

- name: Crear subdirectorio si no existe
  ansible.builtin.file:
    path: /root/rhel7_openscap_result
    state: directory

- name: Creando reporte OpenScap RHEL7 
  ansible.builtin.command: oscap xccdf eval \
    --profile xccdf_org.ssgproject.content_profile_cis_server_l1 \
    --results-arf /root/rhel7_openscap_result/rhel7_reforzamiento_{{ inventory_hostname }}.xml \
    --report /root/rhel7_openscap_result/rhel7_reforzamiento_{{ inventory_hostname }}.html \
    /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
  register: rhel_7_informe_reforzamiento
  ignore_errors: true
