---
#Uninstall avahi Server Package
- name: Ensure avahi is removed
  package:
    name: avahi
    state: absent
  tags:
  - CCE-86511-3
  - NIST-800-53-CM-6(a)
  - NIST-800-53-CM-7(a)
  - NIST-800-53-CM-7(b)
  - disable_strategy
  - low_complexity
  - low_disruption
  - medium_severity
  - no_reboot_needed
  - package_avahi_removed

