---
- name: Obtener la fecha y hora actual
  ansible.builtin.set_fact:
    current_datetime: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
    
- name: Crear subdirectorio si no existe
  ansible.builtin.file:
    path: /home/runner/reportes_openscap_servidores_rhel/{{ inventory_hostname }}
    state: directory
  delegate_to: localhost

- name: copiar archivo html a local EE
  ansible.builtin.fetch:
    src: /root/rhel7_openscap_result/rhel7_reforzamiento_{{ inventory_hostname }}.html
    dest: /home/runner/reportes_openscap_servidores_rhel/{{ inventory_hostname }}/
    flat: yes
  become: yes

- name: cambiar nombre de archivo
  ansible.builtin.shell: "mv /home/runner/reportes_openscap_servidores_rhel/{{ inventory_hostname }}/rhel7_reforzamiento_{{ inventory_hostname }}.html /home/runner/reportes_openscap_servidores_rhel/{{ inventory_hostname }}/rhel7_reforzamiento_{{ inventory_hostname }}_{{ current_datetime }}.html"
  delegate_to: localhost
