---
- name: Validacion de version de sistema operativo
  block:
  
    - name: subproceso de reforzamiento RHEL7
      ansible.builtin.include_tasks: openscap_rhel7.yml
      when: ansible_distribution_major_version  == "7"

    - name: subproceso de reforzamiento RHEL8
      ansible.builtin.include_tasks: openscap_rhel8.yml
      when: ansible_distribution_major_version  == "8"
      
    - name: subproceso de reforzamiento RHEL9
      ansible.builtin.include_tasks: openscap_rhel9.yml
      when: ansible_distribution_major_version  == "9"
  
  when: ansible_distribution == "RedHat"
