---
- name: habilitacion de puertos http RHEL7
  ansible.builtin.include_tasks: rhel7/rhel7_firewall_http.yml

- name: habilitacion de puertos oracle RHEL7
  ansible.builtin.include_tasks: rhel7/rhel7_firewall_oracle.yml

- name: habilitacion de puertos sap RHEL7
  ansible.builtin.include_tasks: rhel7/rhel7_firewall_sap.yml

- name: habilitacion de puertos sial lobo RHEL7
  ansible.builtin.include_tasks: rhel7/rhel7_firewall_sial_lobo.yml

- name: habilitacion de puertos weblogic RHEL7
  ansible.builtin.include_tasks: rhel7/rhel7_firewall_weblogic.yml

- name: recoleccion de datos 
  ansible.builtin.include_tasks: rhel7/rhel7_recoleccion_informacion.yml