---
- name: Clonando repositorio Bitbucket en entorno de ejecucion 
  hosts: localhost
  gather_facts: true 
  roles:
    - bitbucket_login

- name: Escaneo y remediacion de vulnerabilidades para nuevas VM
  hosts: all
  gather_facts: true
  roles:
    - reforzamiento_seguridad_nuevas_vm

- name: subiendo cambio y cerrando conexion a bitbucket
  hosts: localhost
  gather_facts: false   
  roles:
    - bitbucket_cerrar