---
- name: inclusion de tareas de configuracion de servicios 
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - disable_host_based_authentication.yml
    - disable_ssh_access_via_empty_passwords.yml
    # - disable_ssh_root_login.yml
  loop_control:
    loop_var: services_item