---
- name: Configurar las variables de entorno para Bitbucket
  set_fact:
    git_username: "{{ lookup('env', 'usuario_git') }}"
    git_password: "{{ lookup('env', 'password_git') }}"
  no_log: true

- name: Eliminar carpeta especificada de bitbucket en entorno de ejecucion
  ansible.builtin.file:
    path: /repositorio_openscap
    state: absent

- name: Clonar repositorio desde Bitbucket
  ansible.builtin.command:
    cmd: git clone http://{{ git_username  }}:{{ git_password }}@172.27.213.17:17990/scm/ansible/reportes_openscap_servidores_rhel.git
    chdir: /
  delegate_to: localhost
  no_log: true

