---
- name: SAP ABAP
  block:
  - name: Agregando puerto al Firewall para ABAP RHEL7
    ansible.posix.firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled 
    loop: "{{ sap_abap }}"

  - name: Habilitando Firewall de RHEL7
    ansible.builtin.service:
      name: firewalld
      enabled: yes

  - name: Recargar firewall de RHEL7 
    ansible.builtin.service:
      name: firewalld
      state: reloaded
  when: aplicativo == "SAP_ABAP"
  
- name: SAP JAVA
  block:
  - name: Agregando puerto al Firewall para ABAP RHEL7
    ansible.posix.firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled 
    loop: "{{ sap_java }}"

  - name: Habilitando Firewall de RHEL7
    ansible.builtin.service:
      name: firewalld
      enabled: yes

  - name: Recargar firewall de RHEL7 
    ansible.builtin.service:
      name: firewalld
      state: reloaded
  when: aplicativo == "SAP_JAVA"